### PR TITLE
Revert "Updating the new layout "

### PR DESCRIPTION
**Pull request by nathangibson**
Reverts biblia-arabica/srophe-eXist-app#131

@wsalesky When I build the new version as an eXist package and install it, I get the following error at /exist/apps/ba/index.html
```
/db/apps/ba/modules/view.xqlerr:FODC0005 exerr:ERROR Document /db/apps/ba/templates/page.html is a binary resource, not an XML document. Please consider using the function util:binary-doc() to retrieve a reference to it. [at line 416, column 9] In function: templates:surround(node(), map(*), xs:string, xs:string?, xs:string?, xs:string?) [-1:-1:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:process-output(element(), map(*), item()*, element(function)) [211:9:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:call(item(), element(), map(*)) [145:37:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:process(node()*, map(*)) [133:51:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:process(node()*, map(*)) [90:9:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql] templates:apply(node()+, function(*), map(*)?, map(*)?) [53:5:/exist/etc/../data/expathrepo/shared-0.9.1/content/templates.xql]
```

The only line that was changed in templates/page.html was https://github.com/biblia-arabica/srophe-eXist-app/commit/6c9687e86389a1adc71a2719cbad0da93f6f6ba0#diff-a88f6ed6b2e9dc30dc0fe31fe710ad9ad78944840d5210f1171536aab946d440R106

Are images not allowed to be inserted this way?

### CODE REVIEW

**Comment by wsalesky** [comment]
@nathangibson This should not cause a problem. In fact when I added the new/updated files to my local install everything ran fine. I suspect something funky in the merge. I will take a look, but can not get to it until Monday.

**Comment by wsalesky** [comment]
@nathangibson It is not necessary to revert this commit. I made a few adjustments to the edits and everything is working. I will leave this open until you confirm it works for you as well. 

Please let all editors know that the HTML pages must be XHTML pages, all tags must be closed, ampersands must be escaped, etc. This problem was caused by a combination of those two issues.

**Comment by nathangibson** [comment]
So I can just close this, right?

**Comment by wsalesky** [comment]
yes, as long as  the main branch tested correctly for you, this pull request is not needed.

**Pull request closed without merging**
